name: Test Datadog to Issues Action

on:
  workflow_dispatch: # Manual testing only
    inputs:
      pr_number:
        description: 'PR number to test (optional)'
        required: false
        type: string
      test_dashboard_id:
        description: 'Datadog dashboard ID to test (optional)'
        required: false
        type: string

jobs:
  test-action:
    runs-on: ubuntu-latest
    name: Test Datadog to Issues
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import .tool-versions
        uses: wasabeef/import-asdf-tool-versions-action@v1.1.0
        id: asdf # ID to reference outputs

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ steps.asdf.outputs.bun }} # Use Bun version from .tool-versions

      - name: Install dependencies
        run: bun install

      - name: Build action
        run: bun run build # Compile TypeScript

      - name: Run Datadog to Issues Action
        id: datadog-to-github-issues
        uses: ./
        with:
          datadog-api-key: ${{ secrets.DATADOG_API_KEY }} # Secret that needs to be manually configured
          datadog-app-key: ${{ secrets.DATADOG_APP_KEY }} # Secret that needs to be manually configured
          github-token: ${{ secrets.GITHUB_TOKEN }} # GitHub's automatic token

      - name: Verify action completion
        run: |
          echo "🧪 Manual test completed"
          echo "✅ Action outcome: ${{ steps.datadog-to-github-issues.outcome }}"
          if [ "${{ steps.datadog-to-github-issues.outcome }}" = "success" ]; then
            echo "📝 Issue URL: ${{ steps.datadog-to-github-issues.outputs.issue-url }}"
          fi
